simworld.cc

Also see https://forum.simutrans.com/index.php?topic=15675
The same changes have been integrated into Standard by Dwachs as https://github.com/aburch/simutrans/commit/15e450b447f644ce87a84cd9b26caec9a70c2f51.

FIX: Enlarging the map crashes if stops exist near certain locations

---

simworld.h

Remove error compilation while compiling nettool.

Fix nettool compilation.

---

simutrans/text/ru.tab

Non critical edition. low priority.
Probably there will be more edits of one-time mistakes seen during the game.

Update ru.tab in russian translate

---

Makefile
config.template
descriptor/vehicle_desc.h
freight_list_sorter.cc
gui/components/gui_convoy_assembler.cc
gui/components/gui_convoy_assembler.h
network/network.cc
simsys_opengl.cc

and a couple of code corrections.

OpenBSD support and further code fixes

---

.gitignore
Makefile
config.template
music/AVF_core-audio_midi.mm
sound/AVF_core-audio_sound.mm

please see https://forum.simutrans.com/index.php?topic=17573.new#new

Use AV Foundation instead of QTKit

---

bauer/wegbauer.cc
simconvoi.cc
vehicle/simvehicle.cc

Please refer the commit history for the detail.

fixes for OTRP features

---

base_texts_experimental.dat
base_texts_experimental_10.2.dat
base_texts_experimental_8.0.dat
gui/convoi_detail_t.cc
gui/money_frame.cc
player/simplay.cc
simconvoi.cc
simtool.cc
simutrans/text/cz.tab
simutrans/text/en.tab
simutrans/text/hr.tab
simutrans/text/it.tab
simutrans/text/ja.tab

Please check the forum for details.

Complement translationable in-game text

---

bauer/hausbauer.cc
simtool.cc

Fix: Made some texts available in network mode translatable

---

simworld.cc

about this thread
https://forum.simutrans.com/index.php/topic,18670.0.html

FIX: Transported goods monthly data was not recorded

---

gui/components/gui_convoy_assembler.cc

Fixed one of several bugs reported in this thread
https://forum.simutrans.com/index.php/topic,19530.0.html

FIX: If electrified vehicle is stored in a depot, it will be locked in forever

---

gui/components/gui_chart.cc

from standard (prissi/Dwachs) r8891, r8896

FIX: decimals in charts not displayed correctly

---

gui/goods_frame_t.cc
gui/goods_frame_t.h
gui/labellist_frame_t.cc
gui/labellist_frame_t.h

This is leakage of comboboxing patch

Sort button to combobox

---

gui/money_frame.cc

https://forum.simutrans.com/index.php/topic,19733.msg185908/topicseen.html#msg185908

FIX: pull-down list overlapping

---

display/simgraph0.cc

fixed simgraph0.cc

---

simplan.cc

git-svn-id: svn://tron.homeunix.org/simutrans/simutrans/trunk@9139
8aca7d54-2c30-db11-9de9-000461428c89

(Dwachs) FIX position of convoi tooltips (correctly scale height)

---

simsys_s2.cc

git-svn-id: svn://tron.homeunix.org/simutrans/simutrans/trunk@9035 8aca7d54-2c30-db11-9de9-000461428c89

FIX: SDL2 window resizing (ceeac/Markus Pristovek, from standard)

---

bauer/brueckenbauer.cc
bauer/brueckenbauer.h
bauer/hausbauer.cc
bauer/tunnelbauer.cc
bauer/tunnelbauer.h
bauer/wegbauer.cc
descriptor/reader/bridge_reader.cc
descriptor/reader/bridge_reader.h
descriptor/reader/tunnel_reader.cc
descriptor/reader/tunnel_reader.h
obj/roadsign.cc
obj/roadsign.h

See also [here](https://forum.simutrans.com/index.php/topic,20197.0.html).

Fix crashes when loading overlaid objects

---

gui/components/gui_factory_storage_info.cc
gui/fabrik_info.cc
gui/factory_chart.cc
simconvoi.cc
simutrans/text/ja.tab

A bug fix and types of marker types to help distinguish between similarly colored chart lines

Factory gui 2

---

display/simgraph0.cc
display/simgraph16.cc
gui/citylist_frame_t.cc
gui/citylist_stats_t.cc

Citylist layout

---

get_pak.sh

Based on commit e4a1d098d3 from Standard.

Update and fix get_pak.sh

---

simworld.cc

also un-reverts the nicer mismatch message changes, which were not the cause of the issue.

Mismatch message fix

---

simhalt.cc

note: I have used ~~the~~ `__PRETTY_FUNCTION__` ~~macro~~ which replaces the manually-typed function signature. If there is any problem with this, it can be changed back.

FIX: segfault caused by new error message with missing halts.

---

obj/gebaeude.cc

https://forum.simutrans.com/index.php/topic,19156.msg181286.html#msg181286
Incorporating standard's commit to fix this bug.

Only one info window per multitle building V2

---

macros.h
obj/label.cc
player/ai_passenger.cc

Old GCCs do not support C++11 anyway

Remove deprecated GCC 2 specific code

---

.gitignore

See forum post: https://forum.simutrans.com/index.php/topic,20431.0.html

CHG: Git should not track local configuration files for Visual Studio

---

obj/baum.cc
obj/baum.h

- Replace magic numbers with symbols (maximum random age; and minimum probability)
- Translate in tree logic: baum→tree; dichte→density; saee→plant

Eliminate magic numbers; English translation

---

network/network.cc

git-svn-id: svn://tron.homeunix.org/simutrans/simutrans/trunk@9029 8aca7d54-2c30-db11-9de9-000461428c89
(cherry picked from commit 3d3a398b238259def238bbdea745616fc0c3a4ac)

Linux server crash fix when clients abort connection (THLeaderH, from standard)

---

simtool.cc

git-svn-id: svn://tron.homeunix.org/simutrans/simutrans/trunk@9513 8aca7d54-2c30-db11-9de9-000461428c89
(cherry picked from commit 0a399d58ae475670d12eeb60a984acf26849b67d)

FIX: building tunnel portals only again (standard)

---

.github/workflows/ci.yml

See https://github.com/freddyhayward/simutrans-extended/actions/runs/450191854 for sample run with this change.

CI: remove dependency for code formatting check

---

gui/kennfarbe.cc

This commit re-introduces the network player color transfer

Fix: transfer player color change over network

---

simmain.cc

Reported on the forum by RanRan https://forum.simutrans.com/index.php/topic,20884.msg195430.html#msg195430

FIX: Disable midi option is not loaded

---

boden/wege/weg.cc
boden/wege/weg.h
dataobj/route.cc
simworld.cc
tpl/ordered_vector_tpl.h
vehicle/simroadtraffic.cc

Further reductions in private car memory usage

---

simconvoi.cc

Explanatory forum thread: https://forum.simutrans.com/index.php/topic,20998.0.html

Fix withdrawn convoy waiting for schedule

---

simdepot.cc

https://forum.simutrans.com/index.php/topic,21041.msg196327/topicseen.html#msg196327

FIX: The prev next button on the depot dialog's gadget is broken.

---

simworld.cc
vehicle/pedestrian.cc
vehicle/simroadtraffic.cc

Details in forum post: https://forum.simutrans.com/index.php/topic,21149.msg197142.html

Narrower debug sums focused on private cars

---

bauer/fabrikbauer.cc
simtool.cc

Factories with auto rotation, built past end of road or at corners, will be oriented as if road continued in front of them, for a more pleasing effect.

Subtle but pleasing improvement to factory auto-rotation

---

README.html
README.md
readme.txt

See https://forum.simutrans.com/index.php/topic,21403.msg199021.html

Readme overhaul

---

.desktop

Just a small quality of live change for people looking to package simutrans-extended in any linux distribution (such as myself). An update to the .desktop file to make it ready-to-use without further modification.

Update .desktop file

---

simutrans/themes/themes.tab

See [this forum post](https://forum.simutrans.com/index.php/topic,21472.new.html#new).

FIX: Unfinished merge in themes.tab

---

gui/components/gui_combobox.h

Partially reverts the code introduced by r10564.

FIX: The behavior of the GUI where the combobox is placed is somewhat broken

---

gui/map_frame.cc

git-svn-id: svn://tron.homeunix.org/simutrans/simutrans/trunk@10600 8aca7d54-2c30-db11-9de9-000461428c89
Co-Authored-By: Markus Pristovsek <5781847+prissi@users.noreply.github.com>

A lttle better vertical scr9illing of minimap

---

gui/components/gui_factory_storage_info.cc
simfab.cc
simfab.h

Bug Fix: factory connection status gui now uses correct stats when industries are linked for multiple wares

Factory link refactor

---

bauer/vehikelbauer.cc
descriptor/obj_base_desc.h
utils/float32e8_t.cc

Fixes https://forum.simutrans.com/index.php/topic,21880.0.html

Some minor fixes

---

gui/building_info.cc

Broken with the fix on 07/29/21

FIX: Station operation judgment is missing

---

gui/components/gui_line_network.cc
gui/components/gui_line_network.h
gui/convoi_info_t.cc
gui/convoi_info_t.h
gui/schedule_list.cc
gui/schedule_list.h

FIX: size calculation of line network diagram tab

FIX: remove placed components itself

---

gui/replace_frame.cc
gui/replace_frame.h

Added a mode to interchange all trains on the same line.
I'm new to contributing to simutrans-extended, any steps required other than a github pull request? Please let me know if there are any other steps (forums, etc.?) that I need to take.

Added mode of replacement.

---

bauer/fabrikbauer.cc
dataobj/route.cc
dataobj/route.h
vehicle/water_vehicle.cc
vehicle/water_vehicle.h

It's working well.  Time to merge it.  This includes the avoid-checking-off-map branch, please merge that first

Ocean route finder

---

bauer/fabrikbauer.cc

Fixes a conceptual error in my previous commit.  Because I usually play early game, I didn't realize that oil rigs supply factories which are never at the shoreline.

Oil rig fix
