- Simutrans-Experimental-BG.vcxproj
- Simutrans-Experimental-BG.vcxproj.filters
- dataobj/settings.cc
- simtypes.h
As loading standard games did not set _way_degridation_fraction_ a division by zero occured when calculating degradation.
> Fixed: loading standard games 

- boden/grund.h
- gui/depot_frame.cc
- player/finance.h
Minor cleanup: make sure opened comments are closed so that gcc emits fewer warnings.
Reduces output of compile with gcc by almost 2000 lines:
```
$ wc -l compile*log             *[master]  (11:36:10)
3408 compile-cleanup.log
5380 compile-upstream.log
```
> Few cleanups to comments so gcc spews less warnings

- simhalt.h
inauguration_time is an unsigned 32 bit value but it's being set from
get_zeit_ms() which returns a 64bit signed value.  If the 64bit signed
value won't fit into the 32 bit type (>4294967291) then it will overflow
and wrap to 0.  This could lead to odd behaviour with industries not
registering with stops midway through a long running game.
Diagnosed here:
http://forum.simutrans.com/index.php?topic=16673.msg160669#msg160669
> fix potential overflow in inauguration_time

- simtool.cc
This is the translation fix pointed out by Vladki in https://forum.simutrans.com/index.php/topic,17889.0.html .
> FIX: translation of Prohibitive %i at tooltips

- revision.jse
This is a fix to go along with commit r8425 from Standard that helps people to always be able to compile Simutrans even if they don't have Git to generate a revision number [as discussed on the forums](https://forum.simutrans.com/index.php/topic,18150.0.html).
The script will now generate an empty `revision.h` file that will allow MSVC to accept compilation but compile with `REVISION` macro undefined instead of randomly showing a crash log and failing to compile.
It will also, hopefully, output warnings on Visual Studio output to make it easier to let people know the consequences of not having a revision number.
> MSVC pre-build script always generate revision.h

- gui/halt_info.cc
Adds station ownership line to halt info window.  Without this, especially in large multiplayer games, it is often confusing to guess to which of the five blue players a station belongs.
> Add station ownership line to info window

- gui/depot_frame.cc
- simconvoi.cc
This uses call_convoi_tool instead attempting to derive schedule from convoy, which caused buggy behaviour when this was being updated.
> FIX: incorrect schedule edited from depot on high latency games

- Makefile
- boden/wege/weg.cc
- convoy.cc
- gui/settings_stats.cc
- music/AVF_core-audio_midi.mm
- obj/roadsign.cc
- simcity.cc
- simworld.cc
This PR fixes a few compilation errors on macOS, as well as run-time crashes and freeze-ups, both for MULTI_THREAD = 0 and 1.
--------------------------------
One perplexing bug I found causes `convoy_t::calc_move` to get stuck in an infinite loop. Specifically, it happens when I compile without `-fno-inline` (i.e. DEBUG < 2 or PROFILE = 2) using clang v9.0.0 on a Mac.
I dug deeper and the problem appears to be how my compiler compiled float32e8_t subtraction in the case where both operands are equal. Here's an example:
```
float32e8_t a(123, 1000);
cout << "a = " << a << endl;
cout << "a - a = " << (a - a) << endl;
// a = 0.123
// a - a = 0.960938
```
This meant the stopping condition for the while loop in `convoy_t::calc_move` could never be reached. Note that this behavior doesn't …
> FIX: Build & run up to title screen without errors on macOS

- descriptor/vehicle_desc.cc
that is calc_running_cost ignores the difference depending on waytype
> FIX: Wrong start date for obsolete costing

- Makefile
Thanks to @ceeac for bring the fact that simutrans actually has sdl2_mixer backend all ready and just needed a `Makefile` update to bring it over to simutrans-extended
Sort-of fixes #215 by replacing with a newer backend.
> Add SDL2_mixer backend

- gui/components/gui_convoy_assembler.cc
- gui/convoi_detail_t.cc
- gui/player_frame_t.cc
- simtool.cc
Old MSVC compilers and MinGW do not support %hhu for printf/scanf properly, leading to desyncs when reassigning a convoi class, changing players, and using the access tool.
> Fix desyncs when using specific tools in network mode

- player/simplay.cc
- simhalt.cc
- simhalt.h
For example, if stop A is connected to an underground stop B, while stop C is unconnected to either but located above stop B, frequency would be calculated from stop A->C and B->A, leaving A->B "unknown".
> FIX: Wrong halts being compared for overlaid stations in frequency calculation

- gui/components/gui_aligned_container.cc
this is a temporary fix that doesn't address the underlying issue - but it will prevent those crashes in the meantime
> fix: crash when clicking on one train staff cabinets and end of signalling signs

- CMakeLists.txt
- Makefile
- dataobj/environment.cc
- dataobj/loadsave.cc
- dataobj/loadsave.h
- dataobj/settings.cc
- gui/loadsave_frame.cc
- gui/settings_frame.cc
- gui/settings_stats.cc
- gui/simwin.cc
- gui/welt.cc
- io/classify_file.cc
- io/classify_file.h
- io/rdwr/bzip2_file_rdwr_stream.cc
- io/rdwr/bzip2_file_rdwr_stream.h
- io/rdwr/raw_file_rdwr_stream.cc
- io/rdwr/raw_file_rdwr_stream.h
- io/rdwr/rdwr_stream.cc
- io/rdwr/rdwr_stream.h
- io/rdwr/zlib_file_rdwr_stream.cc
- io/rdwr/zlib_file_rdwr_stream.h
- io/rdwr/zstd_file_rdwr_stream.cc
- io/rdwr/zstd_file_rdwr_stream.h
- network/network_cmd_ingame.cc
- network/network_file_transfer.cc
- simfab.cc
- siminteraction.cc
- simmain.cc
- simworld.cc
- simworld.h
CODE: Add rdwr_stream_t to read or write data
ADD: classify_file() to determine file format
FIX: Data race potentially causing hang when reading zstd saves multi-threaded
Cherry-pick of commit 1f61ea16e from Standard.
> Refactor save/load to use read/write streams

- simhalt.cc
The path explorer correctly explored the prioritymail network but express mail used the precalculated normal mail network to move around.
This effectively led to pure express mail routes being entirely ignored by any mail (except from very small amounts of mail. It is yet unclear to me how those few units made their way into pure priority mail routes)
This fix also comes with a slight code cleanup as it was caused by a mistaken conditional handling where no condition was needed at all.
> Fix: Pure express mail routes were ignored by express mail

- display/simgraph.h
- display/simgraph0.cc
- display/simgraph16.cc
- display/simview.cc
- display/simview.h
- gui/components/gui_building.cc
- gui/components/gui_convoy_assembler.h
- gui/components/gui_speedbar.cc
- gui/components/gui_table.h
- gui/components/gui_textarea.cc
- gui/components/gui_textinput.cc
- gui/convoi_detail_t.cc
- gui/convoi_detail_t.h
- gui/gui_theme.cc
- gui/gui_theme.h
- gui/halt_detail.cc
- gui/halt_list_stats.cc
- gui/map_frame.cc
- gui/minimap.cc
- gui/minimap.h
- gui/simwin.cc
- obj/simobj.cc
- simhalt.cc
- simhalt.h
- simloadingscreen.cc
- simworld.cc
- vehicle/simvehicle.cc
This PR includes the following changes:
Fix: Do not show stop coverage on farm fields
Fix: Prevent overflows caused by some minimap layers on huge maps
Fix: The "Stop coverage" layer did not work properly with the "All freight Types" filter
Change: Companies without convoys (pure infrastructure companies) can now be selected in minimaps company filter.
Code cleanup of minimap.cc and minimap.h
> Minimap fixes

- Makefile
- config.default.in
- config.template
- dataobj/ribi.cc
- dataobj/ribi.h
Modified `ribi` to avoid Look-Up-Tables to hypothetically increase performance.
Also adjusted Makefile to reflect conditional compilation of some such optimizations.
Additionally, enabled Link Time Optimizations (LTO).
As each column of the `ribi_t::flags` Look-Up Table is 16 bits, such columns are flattened into the `ribi_t` functions using such flags.  After compilation, this replaces the _address calculation_, _load_, _and_ with a _Load Immediate_, _shift_, _and_ on the x86 and x86_64.  Likewise, for 64 bit machines, the `ribi_t::backwards`, `ribi_t::doppelr`, and `ribi_t::dirs` have their LUTs flattened to 64 bit longs, resulting in a _shift_, _Load Immediate_, _shift_, _and_.  `is_straight_{ns,ew}` functions have been simplified to an _or_, _compare_.  Additionally, when compiling …
> Low Level performance optimizations for ribi_t

- simworld.cc
Previously, cities_awaiting_private_car_route_check saved using cities center position, which in rare cases would move outside of the city when loading.
> FIX: cities_awaiting_private_car_check saves fixed city position

- simcity.cc
- simcity.h
private_car_destination_finder: made speed calculation more linear to recorded congestion information and removed erroneous caching of cost.
> Private car routing improvements

- player/finance.h
- player/simplay.cc
The takeover cost calculation seems to be broken.
The first commit fixes those calculations.
The new behavior is the following:
- Takeover costs are calculated as "assets - account_balance" if the company is not in liquidation
- Takeover costs ammount in just the assets if the company is in liquidation
The second commit adds an additional cost to takeovers ammounting in the start capital of the current year to prevent the takeover exploit.
> Company takeover fixes

- gui/trafficlight_info.cc
- gui/trafficlight_info.h
- obj/roadsign.cc
- obj/roadsign.h
- simtool.cc
- simversion.h
- vehicle/simroadtraffic.cc
This patch introduces yellow light that enables to prevent the car from entering the intersection while transitioning phases.
The default duration of phases is as follows:
N-S direction (16s)→ N-S yellow (2s) → E-W direction (16s) → E-W yellow (2s) → ...
and now the yellow light image can be used when the images are listed in image[17]-[31]. If those are not defined, green light images are used instead of yellow light.
> Yellow light

- bauer/fabrikbauer.cc
- gui/factory_edit.cc
- simtool.cc
Add Auto rotation in factory creation dialog, and always auto-rotate factories created during world creation. Results in much-nicer looking cities.
> Auto factory rotation capability

- simcity.cc
I identified some issues with my previous implementation which led to city growth malfunctioning on paksets without the new values defined and cities developing slowly increasing gulfs between resident and job numbers due to miscalculation in resident numbers led to unwanted bias in building development
> Renovation1

- CMakeLists.txt
- Makefile
- Simutrans-Extended.vcxproj
- dataobj/environment.cc
- dataobj/environment.h
- dataobj/settings.cc
- gui/display_settings.cc
- gui/display_settings.h
- gui/pedestrian_info.cc
- gui/pedestrian_info.h
- gui/settings_stats.cc
- gui/way_info.h
- simintr.cc
- simline.cc
- simline.h
- simtypes.h
- simutrans/config/simuconf.tab
- simutrans/text/ja.tab
- simversion.h
- vehicle/pedestrian.cc
- vehicle/pedestrian.h
- vehicle/simroadtraffic.cc
This branch builds upon the latest changes of Ranran's appreciated detach-ped-info branch
On top of the changes made there, it adds the following:
- split the pedes_and_car_info simuconf attribute into pedestrian_info and privatecar_info
- split the show_names simuconf attribute into how_station_names, show_station_statistics and station_label_style
- adjust simuconf, so all settings from the display settings UI are commented out in simuconf and reside in their own category.
- removed display setting UI settings from advanced settings UI
These changes aim so solve multiple minor issues:
- More consistency in between the ingame UI and simuconf.
pedes_and_car_info as well as show_names have been split in the display settings UI whilst being combined attributes in simuconf.
- Setting any …
> Simuconf display setting refinements

- CMakeLists.txt
SIMUTRANS_ENABLE_RANDOMNESS CMake flag has been replaced with SIMUTRANS_DISABLE_RANDOMNESS which is more appropriately since the default behaviour is for the randomness to be enabled.
> FIX: Enable randomness by default for the CMake build

- CMakeLists.txt
Added link_directories variable so CMake knows where Homebrew libraries are located on Apple silicon Macs, as explained [here](https://www.reddit.com/r/MacOS/comments/jw9guu/why_did_homebrew_move_from_usrlocalto_opthomebrew/).
Compilation has been tested successfully:
> Added link_directories for Apple silicon Homebrew path.

- bauer/fabrikbauer.cc
- obj/gebaeude.cc
- obj/gebaeude.h
- simcity.cc
- simcity.h
- simversion.h
- simworld.cc
- simworld.h
The final stage (for now) in my minor prettification campaign.  This includes the other two pull requests.
Now, when building a road from a factory to a city, the factory will first look for a rectangularly adjacent existing road; then a diagonally adjacent existing road; then pick a *random* rectangularly adjacent empty spot.  If that doesn't work it will go through the remaining rectangularly adjacent empty spots, and finally the diagonally adjacent empty spots.  Preferring the rectangular adjacency makes it look better.  The random choice gives more diversity of layout (it was always preferring the top left before).
Roads will be built from a factory to a city even for factories within a city -- this is to aid shore_city and river_city factories, which will now find an appropriate …
> More varied factory connections

- bauer/wegbauer.cc
- bauer/wegbauer.h
I figured out why the roads to industries were not building river fords.  They set a flag to forbid_crossings, which is intended to avoid creating grade crossings across player railways.  But it was forbidding all crossings.  This patches it so that this flag (which is only used for this purpose) allows the creation of fords across non-navigable rivers.
With this fixed, we should stop having so many prebuilt stone bridges in 1750 maps.  Hooray!
> FIX: Allow river fords on roads to industries!

- simcity.h
- simtool.cc
Make existing function get_best_layout() in stadt_t public, as we wish to use it in simtool.cc. This replaces a less-thorough copy with the 'real thing.' Rename array in simtool.cc as 'neighbours_of_diag' to clarify its purpose.
> Prefer existing function 'get_best_layout' in city building autorotate

- player/simplay.cc
- simworld.cc
This patch was mentioned in the standard forum a while ago, and since it's a small change I thought I'd create and post a patch before it fades into oblivion.
Although notification messages are provided when a company is taken over or player nickname is changed, there are no notifications when a company is founded or company name is changed, resulting in inconsistent behavior and delaying the opportunity for uninvolved players to become aware of the facts.
> CHG: announce the player's foundation and name change.
